name: athendat
description: "A simple ecommerce to athendat company."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  sliding_up_panel: ^2.0.0+1
  dio: ^4.0.6
  get_it: ^7.6.4
  retrofit: ^3.3.1
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.1
  connectivity_plus: ^4.0.2
  fpdart: ^1.1.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.0.0
  provider: ^6.0.5
  window_manager: ^0.3.7
  image_picker: ^1.0.4
  file_selector: ^1.0.1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  equatable: ^2.0.5
  simple_animations: ^5.0.2
  translator: ^0.1.7
  cached_network_image: ^3.3.0
  image: ^4.2.0
  auto_size_text: ^3.0.0
  uuid: ^4.5.1
  infinite_scroll_pagination: ^4.1.0
  lazy_load_scrollview: ^1.3.0

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  retrofit_generator: ^4.2.0
  json_serializable: ^6.7.1
  bloc_test: ^9.1.4



flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
 
  assets:
    - assets/images/
  